name: Create 404 Page
on:
  push:
    branches:
      - deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "index.html"
          target: "404.html"